name: Build Custom IES s2i image (with ghostscript)

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/build-ies-s2i-image.yml"
      - "14"
      - "16"
      - "ddk.txt"
  workflow_dispatch:

env:
    IMAGE_NAME: ies-s2i-nodejs-container
    IMAGE_TAGS: dev ${{ github.sha }}
    IMAGE_REGISTRY: ghcr.io/${{ github.actor }}
    REGISTRY_USER: ${{ github.actor }}
    REGISTRY_PASSWORD: ${{ github.token }}

jobs:

  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: List Directory Contents
      run: |
        pwd
        ls -laR ./14

    - name: Buildah Action
      id: build_image
      uses: redhat-actions/buildah-build@v2
      with:
        context: |
          ./14
        image: ${{ env.IMAGE_NAME }}
        tags: ${{ env.IMAGE_TAGS }}
        containerfiles: |
          ./14/Dockerfile

      # Push the image to GHCR (Image Registry)
    - name: Push To GHCR
      uses: redhat-actions/push-to-registry@v2
      id: push
      with:
        image: ${{ steps.build_image.outputs.image }}
        tags: ${{ steps.build_image.outputs.tags }}
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ env.REGISTRY_USER }}
        password: ${{ env.REGISTRY_PASSWORD }}
        extra-args: |
          --disable-content-trust
    - name: Echo outputs
      run: |
        echo "${{ toJSON(steps.push.outputs) }}"



